name: tfrrs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - selenium
  - beautifulsoup4
  - pip
  - pip:
      - undetected-chromedriver
      - fake-useragent
      - playwright